In [3]:
import numpy as np
A = np.array([[2,3],[5,6],[1,7]])
B = np.array([[4,1,5,0],[3,2,6,3]])

print(all(A[1,:] == B[:,2]))

True


In [7]:
nRows = 3
nColumns = 3
zeroMatrix = np.zeros((nRows,nColumns))

In [4]:
C = np.concatenate(B.copy(), B)

NameError: name 'B' is not defined

In [5]:
import numpy as np
C = np.concatenate(B.copy(), B)

NameError: name 'B' is not defined

In [6]:
import numpy as np
A = np.array([[2,3],[5,6],[1,7]])
B = np.array([[4,1,5,0],[3,2,6,3]])

print(all(A[1,:] == B[:,2]))

True


In [13]:
import numpy as np
A = np.array([[2,3],[5,6],[1,7]])
B = np.array([[4,1,5,0],[3,2,6,3]])

print(all(A[1,:] == B[:,2]))
C = B.copy()
C = np.concatenate((C,B))
C[:,1] = np.array([4,3,2,1])
print(C)
print(B)

True
[[4 4 5 0]
 [3 3 6 3]
 [4 2 5 0]
 [3 1 6 3]]
[[4 1 5 0]
 [3 2 6 3]]
